config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'widgets#index'

  resources :widgets
  get 'possibilities', to: 'widgets#all'

  get 'kittens' => 'async#index'
  get 'kitten'  => 'async#kitten'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/multi_enum.rb
require "active_support/concern"

module MultiEnum
  extend ActiveSupport::Concern

  included do
    # subtract options_hash_values starting with largest, until left with 0
    # this should return list of all options as integer array
    def option_ids
      x = option_id
      self.class.options_hash_values.select{ |n| (x - n).negative? ? next : x -= n }
    end

    # converts option_ids integers to array of matching names from option_list
    def options
      hash = self.class.options_hash.invert
      option_ids.sort.map{|id| hash[id] }
    end
  end

  class_methods do
    # Convert array of names into a hash with sequentially doubling values
    def options_hash(n = 1, o = self::OPTIONS)
      (n..(o.count - 1)).map{ |x| [o[x], n *= 2] }.prepend([o[0], 1]).to_h
    end

    # return all option_hash integer values from largest to smallest
    def options_hash_values
      options_hash.values.sort.reverse
    end

    ######## Finder methods ########

    # Find all possible option_ids for a given option_list item
    def ids_for_option(option = nil)
      id = options_hash.with_indifferent_access[option]
      possibilities = (0..max_option_id).map{|s| [s, self.new(option_id: s).option_ids ] }.to_h
      ids = possibilities.select{|k,v| v.include?(id) }.keys
    end

    # find by single option
    def find_by_option(option = nil)
      where(option_id: ids_for_option(option))
    end

    # find by array of options
    def find_by_options(options = [])
      ids = options.map{|option| ids_for_option(option) }.flatten
      where(option_id: ids)
    end

    ####### Test methods - not required to work #######

    # return the total possible number of combinations based on count from option_list
    def max_option_id
      (options_hash.values.max * 2) - 1
    end

    # return all combinations and how to achieve them
    def test
      (0..max_option_id).map{|s| [s, self.new(option_id: s).option_ids.join(' + ')].join(' = ') }
    end
  end

end

app/models/post.rb
class Post < ApplicationRecord
  include PgSearch::Model
  pg_search_scope :search,
    against: {
      title: 'A',
      body: 'B'
    },
    using: {
      tsearch: {
        prefix: true
      }
    }
end

app/models/widget.rb
class Widget < ApplicationRecord
  # Setup option names
  OPTIONS = [:apples, :bananas, :blueberries, :coconuts, :grapes, :lemons, :peaches, :raspberries, :strawberries, :watermelons, :cherries].freeze

  include MultiEnum
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/async_controller.rb
class AsyncController < ApplicationController

  def index
  end

  def kitten
    @image = get_cat_image
  end

  private

  def get_cat_image
    url = 'https://api.thecatapi.com/v1/images/search'
    resp = Net::HTTP.get(URI(url))
    JSON.parse(resp)[0]['url']
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = get_posts
  end

  private

  def get_posts
    return Post.search(params[:search]) if params[:search].present?

    Post.all
  end
end

app/controllers/widgets_controller.rb
class WidgetsController < ApplicationController
  before_action :set_widget, only: %i[ show edit update destroy ]
  before_action :set_option_id, only: %i[ create update ]

  # GET /widgets or /widgets.json
  def index
    @widgets = get_widgets
  end

  # GET /widgets/1 or /widgets/1.json
  def show
  end

  # GET /widgets/new
  def new
    @widget = Widget.new
  end

  # GET /widgets/1/edit
  def edit
  end

  # POST /widgets or /widgets.json
  def create
    @widget = Widget.new(widget_params)

    respond_to do |format|
      if @widget.save
        format.html { redirect_to edit_widget_path(@widget), notice: "Widget was successfully created." }
        format.json { render :show, status: :created, location: @widget }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @widget.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /widgets/1 or /widgets/1.json
  def update
    respond_to do |format|
      if @widget.update(widget_params)
        format.html { redirect_to edit_widget_path(@widget), notice: "Widget was successfully updated." }
        format.json { render :show, status: :ok, location: @widget }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @widget.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /widgets/1 or /widgets/1.json
  def destroy
    @widget.destroy
    respond_to do |format|
      format.html { redirect_to widgets_url, notice: "Widget was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def all
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_widget
      @widget = Widget.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def widget_params
      params.require(:widget).permit(:name, :option_id)
    end

    def set_option_id
      params[:widget][:option_id] = params[:widget][:options]&.map(&:to_i)&.sum.to_i
    end

    def get_widgets
      return Widget.find_by_option(params[:search]) if params[:search].present?

      Widget.all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/widgets_helper.rb
module WidgetsHelper
end

app/views/async/_add_kitten.html.haml
.random-kitten
  = image_tag(@image, height: 480)

app/views/async/index.html.haml
%h1 Welcome to the random kitten page!

.kitten-generator
  = link_to 'Show me kittens', kitten_path, remote: true, class: 'btn'

.kittens

app/views/async/kitten.js.erb
document.getElementsByClassName('kittens')[0].innerHTML = '<%= escape_javascript(render "add_kitten") %>';

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AsyncTest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_list.html.haml
- @posts.each do |post|
  %tr
    %td= post.title
    %td= post.body
    %td= post.published

app/views/posts/_search.html.haml
= form_tag posts_path, method: :get, remote: true, id: 'search-form' do
  = search_field_tag :search, nil, id: 'search-field'
  = submit_tag 'Search'

:javascript
  let timer;
  let waitTime = 250;
  document.getElementById('search-field').addEventListener('keyup', function(){
    clearTimeout(timer);
    timer = setTimeout(search, waitTime);
  });

  function search () {
    document.forms['search-form'].requestSubmit();
  }

app/views/posts/index.html.haml
%h1 Listing posts

= render 'shared/search'

%hr

%table
  %thead
    %tr
      %th Title
      %th Body
      %th Published
      %th{colspan: 3}

  %tbody#list
    = render 'list'

app/views/shared/_search.html.haml
= form_tag '', method: :get, remote: true, id: 'search-form' do
  = search_field_tag :search, nil, id: 'search-field'
  = submit_tag 'Search'

:javascript
  let timer;
  let waitTime = 250;
  document.getElementById('search-field').addEventListener('keyup', function(){
    clearTimeout(timer);
    timer = setTimeout(search, waitTime);
  });

  function search () {
    document.forms['search-form'].requestSubmit();
  }

app/views/widgets/_form.html.haml
= form_for @widget do |f|
  - if @widget.errors.any?
    #error_explanation
      %h2= "#{pluralize(@widget.errors.count, "error")} prohibited this widget from being saved:"
      %ul
        - @widget.errors.full_messages.each do |message|
          %li= message

  .form-group
    = f.label :name
    = f.text_field :name

  .form-group
    = f.label :option_id, "Options"
    - Widget.options_hash.each do |name, id|
      .div
        = check_box_tag 'widget[options][]', id, @widget.option_ids.include?(id)
        = "#{name} - #{id}"
  .form-group
    Option ID:
    %b= @widget.option_id

  .actions
    = f.submit 'Save'

app/views/widgets/_info.html.haml
:javascript
  document.getElementById('show-info').addEventListener('click', function(e){
    e.preventDefault();
    let el = document.getElementById('info');
    if (el.style.display == 'block') {
      el.style.display = 'none';
      this.textContent = 'More Details..';
    }
    else {
      el.style.display = 'block';
      this.textContent = 'Nevermind, less details';
    }
  });

.info{id: 'info', style: 'display: none;'}
  .form-group
    %div= image_tag('https://media.giphy.com/media/Vy9bLZxNutIlLuNXOZ/giphy.gif')
    %h2 What is this?
  .form-group
    This model only has 3 fields:
    %code id:integer
    ,
    %code name:string
    and
    %code option_id:integer
    , but can save a collection of options (multi-select) stored as a single integer.
  .form-group
    There are no join tables or array columns, just an integer column and a model concern.

  %hr
  .form-group
    %div= image_tag('https://media.giphy.com/media/X4YqmJEl6wJoY/giphy.gif')
    %h2 Why?
  .form-group
    Imagine the simplicity of the
    = link_to 'Rails enum', 'https://api.rubyonrails.org/v5.2.4.4/classes/ActiveRecord/Enum.html', target: '_blank'
    feature mixed with the flexibility of a
    = link_to 'Postgres Array string field.', 'https://guides.rubyonrails.org/active_record_postgresql.html#array', target: '_blank'
    %div I really like the idea of the Rails enum, essentially mapping an integer to a more meaningful string. It seems like the most efficient way to store data in a database.

  .form-group
    %div
      I have played with ActiveRecord/Postgres arrays, and that is always been an appealing idea when you need to store an array of data but don't really feel that it warrants its own database-table/model.
    %div
      My biggest gripe about that is that the Postgres array route requires storing a potentially long string in the database and the queries are just plain wacky:
    %div
      %code Book.where("tags @> ARRAY[?]::varchar[]", ["fantasy", "fiction"])
  .form-group
    %div So I began wondering what it would look like or if it would be possible to represent an array of data as a single integer... this was what I came up with.

  %hr
  .form-group
    %div= image_tag('https://media.giphy.com/media/10yIEN8cMn4i9W/giphy-downsized.gif')
    %h2 How?
  .form-group
    %div
      I got the idea while thinking about
      = link_to 'unix permissions', 'http://permissions-calculator.org/', target: '_blank'
      where each permission type is assigned a number (read => 1, write => 2, execute => 4), and combining those numbers gives you the flexibility to represent any permission type you want with a single digit (r=read, w=write, x=execute): 1=r, 2=w, 3=rw, 4=x, 5=rx, 6=wx, 7=rwx. This made me realize that if you scaled that out, you could add as many options as you wanted and still have just one integer representation.
  .form-group
    %div So we can provide a list of options, then dynamically calculate the integer value for each one in the array by doubling the previous value. Also added in some methods to query by an option (click one of the Fruit name filters above) and a method to convert a given integer into the list of options.
  .form-group
    %div You can add any combination of these integer values to form a unique single integer value that represents a specific collection.

  .form-group
    Click here to see all of the
    = link_to "#{Widget.test.count - 1} possible combinations", possibilities_path, target: '_blank'
    for the
    = Widget::OPTIONS.count
    options available and the number that represents each.

  %hr
  .form-group
    %div= image_tag('https://media.giphy.com/media/l0Iy8N8khDX5AElgI/giphy-downsized.gif')
    %h2 Disclaimer:
  .form-group
    This is merely a proof of concept.
    %div There are likely reasons why you wouldn't want to do this on a production app and I haven't thought through all the pros/cons, but it was such a neat idea and I wanted to play with it.
  .form-group
    %div
      This is the entire Widget model:
      %code
        %pre
          %div= 'class Widget < ApplicationRecord'
          %div= '  # Setup option names'
          %div= '  OPTIONS = [:apples, :bananas, :blueberries, :coconuts, :grapes, :lemons, :peaches, :raspberries, :strawberries, :watermelons, :cherries].freeze'
          %div= '  include MultiEnum'
          %div= 'end'
      = link_to 'Here is the relevant code', 'https://github.com/johndavid400/async-test/blob/master/app/models/concerns/multi_enum.rb', target: '_blank'
      if you are interested (about 50 lines of ruby).

  .form-group
    The values of each option are shown next to their name in the filters and on the edit page.

app/views/widgets/_list.html.haml
- @widgets.each do |widget|
  %tr
    %td= widget.name
    %td= widget.option_id
    %td= widget.options.join(', ')
    %td= link_to 'Edit', edit_widget_path(widget)
    %td= link_to 'Destroy', widget, method: :delete, data: { confirm: 'Are you sure?' }

app/views/widgets/_widgets.html.haml
.title
  = link_to "View All", widgets_path, remote: true, :'data-no-turbolink' => true, class: 'button'
  - Widget.options_hash.each do |key, value|
    = link_to "#{key.to_s.titleize} (#{value})", widgets_path(search: key), remote: true, :'data-no-turbolink' => true, class: 'button'

app/views/widgets/all.html.haml
.form-group
  %h3= "All possible combinations (#{Widget.test.count - 1}):"
  (don't worry, this is generated)
  .form-group
    = link_to 'Go Back', widgets_path
  %hr
  - Widget.test.each do |s|
    - unless s == "0 = "
      .form-group
        = s

app/views/widgets/edit.html.haml
%h1 Editing widget

= render 'form'

= link_to 'Back to index', widgets_path

app/views/widgets/index.html.haml
%h1 Multi-Enum
Storing a collection of items as a single integer (with no join tables).
The Widget table below has only
%code id:integer
,
%code name:string
,
and
%code option_id:integer
columns.

%hr

%h4 Feel free to play around and see how it works

= render 'widgets'

%table#widgets
  %thead
    %tr
      %th Name
      %th Option ID
      %th Options
      %th{colspan: 2}

  %tbody#list
    = render 'list'

%br

= link_to 'New Widget', new_widget_path, class: "button new"
%hr
= link_to "More Details..", "#", id: 'show-info', class: "button"

.form-group
  = render 'info'

app/views/widgets/index.js.erb
// Vanila JS used to target the element we want to update, then replace its HTML with the contents of the 'list' partial.

// Note: any instance variables set in the controller will be available here and in the partial when rendered (ie. @posts),
// so you don't have to explicitly pass those in as a local variable unless you just want to.
document.getElementById('list').innerHTML = '<%= escape_javascript(render "list") %>';

//// If using jQuery, you can do this slightly shorter version:
// $('#list').html('<%= escape_javascript(render "list") %>';

app/views/widgets/new.html.haml
%h1 New widget

= render 'form'

= link_to 'Back to index', widgets_path

app/views/widgets/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_widget_path(@widget)
\|
= link_to 'Back', widgets_path